package model;


/**
 * JTunes - SISTEMA PARA VENDA DE MÚSICAS ONLINE SEMELHANTE AO ITUNES.
 * SERVLET CONTROLA COMPRA.
 *
 * @author VANDERSON DINIZ
 * @author ERICK SILVA
 * @version JTUNES 1.0 
 */


/**CLASSE PESSOA EM CONSTRUÇÃO.
 * NA VERSÃO JTUNES 2.0, SERÁ CRIADA UMA INTERFACE 
 * ONDE SEJA POSSÍVEL UTILIZAR OS DADOS DA CLASSE PESSOA, 
 * PARA AS DEMAIS CLASSES QUE POSSUAM SEMELHANÇAS.
 * */


public class Pessoa {

}
